services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
    networks:
      - radar_network

  frontend:
    build:
      context: ../frontend/radar_frontend
      dockerfile: ../../docker/Dockerfile.frontend
    working_dir: /app
    volumes:
      - ../frontend/radar_frontend:/app:cached
    ports:
      - '5212:5212'
      - '5679:5678'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
    networks:
      - radar_network
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - radar_network

volumes:
  mongo_data:
  mongo_config:

networks:
  radar_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
